exclude: [rebuildghpages, devserve, Gemfile, Gemfile.lock]
description: A blog dedicated to mathematics, linguistics, reason, and somewhat my personal life
future: false
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
google-analytics: UA-99443259-1
name: Justen Rickert
title: Justen Rickert
